# Generated by Django 3.2.7 on 2021-09-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
